-- Minimal seed users for local demos.
-- Password hashes are placeholders; prefer creating users through /api/auth/register
-- so BCrypt hashes are generated by the application.

INSERT INTO users (username, email, password_hash)
VALUES
  ('ash', 'ash@example.test', '$2a$10$replace-with-real-hash'),
  ('misty', 'misty@example.test', '$2a$10$replace-with-real-hash')
ON CONFLICT (username) DO NOTHING;

-- Cards are seeded by the backend catalog bootstrap from pokemontcg.io set xy1.
-- After cards are present, demo decks should be created through the Deck Builder
-- API so validation flags and deck_cards stay consistent.
