spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:55432/pokemontcg}
    username: pokemontcg
    password: pokemontcg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8081

logging:
  level:
    com.utn.pokemontcg: DEBUG
    org.hibernate.SQL: DEBUG
